[build-system]
requires = ["uv_build>=0.7.19,<0.8.0"]
build-backend = "uv_build"

[project]
name = "cast-bootstrap5"
version = "0.0.77"
description = "Bootstrap5 theme for django-cast"
authors = [
    { name = "Jochen Wersdörfer", email = "jochen-castbootstrap5@wersdoerfer.de" },
]
requires-python = ">=3.11"
keywords = ["blog", "podcast", "video", "audio"]
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.2",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Topic :: Internet",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

dependencies = ["django-cast>=0.2.62", "crispy-bootstrap5"]

[project.optional-dependencies]
test = ["pytest >= 6", "pytest-cov >= 3", "pytest-django", "pytest-mock"]
doc = ["furo"]
dev = [
    "black",
    "flake8",
    "django-environ",
    "django_extensions",
    "django-stubs[compatible-mypy]",
    "isort",
    "jupyter",
    "mypy",
    "rich",
    "tox",
    "typer",
]

[project.urls]
Documentation = "https://github.com/ephes/cast-bootstrap5#readme"
Source = "https://github.com/ephes/cast-bootstrap5"


[tool.uv.build-backend]
module-root = ""
module-name = "cast_bootstrap5"

[tool.isort]
profile = "black"

[tool.black]
line-length = 119

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning"]
addopts = ["-ra"]
